### ISSUE TITLE
Typo in description of metronome-validator/lib/chain.js

### ISSUE THREAD

**Issue by Dareknotderek** [autonomoussoftware/metronome-validator#3]
@hitli001 noticed a typo on line 32 of `metronome-validator/lib/chain.js`

passord should = password - see attachment 

![photo5785155312754471305](https://user-images.githubusercontent.com/32199587/59715562-c628bc80-91d9-11e9-95db-0a75c876a4c8.jpg)

**Comment by patidarmanoj10** [comment]
Thanks for reporting this. This has been fixed.
